version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: development
    command:
      - "npx"
      - "webpack"
    environment:
      NODE_ENV: "development"
    env_file:
      - ".env"
    volumes:
      - ./:/app:rw
    ports:
      - "3030:3030"
    networks:
      - eve-storage

networks:
  eve-storage:
    external: true
